export const aePlugin = {
  label: "AE插件开发",
  link: "ae-plugin/intro/what-can-i-do",
  icon: "puzzle",
  items: [
    {
      label: "Introduction",
      items: [
        "ae-plugin/intro/what-can-i-do",
        "ae-plugin/intro/other-integration-possibilities",
        "ae-plugin/intro/sdk-audience",
        "ae-plugin/intro/whats-new",
        "ae-plugin/intro/how-to-start-creating-plug-ins",
        "ae-plugin/intro/sample-projects",
        "ae-plugin/intro/debugging-plug-ins",
        "ae-plugin/intro/compatibility-across-multiple-versions",
        "ae-plugin/intro/third-party-plug-in-hosts",
        "ae-plugin/intro/pipl-resources",
        "ae-plugin/intro/exceptions",
        "ae-plugin/intro/where-installers-should-put-plug-ins",
        "ae-plugin/intro/localization",
        "ae-plugin/intro/apple-silicon-support",
        "ae-plugin/intro/symbol-export",
        "ae-plugin/intro/next-steps",
      ],
    },
    {
      label: "Effect Basics",
      items: [
        "ae-plugin/effect-basics/effect-basics",
        "ae-plugin/effect-basics/entry-point",
        "ae-plugin/effect-basics/command-selectors",
        "ae-plugin/effect-basics/pf_indata",
        "ae-plugin/effect-basics/pf_outdata",
        "ae-plugin/effect-basics/parameters",
        "ae-plugin/effect-basics/pf_paramdef",
        "ae-plugin/effect-basics/pf_effectworld",
        "ae-plugin/effect-basics/errors",
      ],
    },
    {
      label: "Effect Details",
      items: [
        "ae-plugin/effect-details/multi-frame-rendering-in-ae",
        "ae-plugin/effect-details/effect-details",
        "ae-plugin/effect-details/accessing-function-suites",
        "ae-plugin/effect-details/memory-allocation",
        "ae-plugin/effect-details/image-buffer-management-functions",
        "ae-plugin/effect-details/iteration-suites",
        "ae-plugin/effect-details/graphics-utility-suites",
        "ae-plugin/effect-details/interaction-callback-functions",
        "ae-plugin/effect-details/pixel-aspect-ratio",
        "ae-plugin/effect-details/parameters-floating-point-values",
        "ae-plugin/effect-details/parameter-supervision",
        "ae-plugin/effect-details/global-sequence-frame-data",
        "ae-plugin/effect-details/arbitrary-data-parameters",
        "ae-plugin/effect-details/useful-utility-functions",
        "ae-plugin/effect-details/motion-blur",
        "ae-plugin/effect-details/working-with-paths",
        "ae-plugin/effect-details/accessing-camera-light-information",
        "ae-plugin/effect-details/color-space-conversion",
        "ae-plugin/effect-details/changing-parameter-orders",
        "ae-plugin/effect-details/tips-tricks",
        "ae-plugin/effect-details/compute-cache-api",
      ],
    },
    {
      label: "SmartFX",
      items: ["ae-plugin/smartfx/smartfx"],
    },
    {
      label: "Effect UI & Events",
      items: [
        "ae-plugin/effect-ui-events/effect-ui-events",
        "ae-plugin/effect-ui-events/pf_eventextra",
        "ae-plugin/effect-ui-events/pf_eventunion",
        "ae-plugin/effect-ui-events/custom-ui-and-drawbot",
        "ae-plugin/effect-ui-events/ui-callbacks",
        "ae-plugin/effect-ui-events/tips-and-tricks",
      ],
    },
    {
      label: "Audio",
      items: [
        "ae-plugin/audio/audio",
        "ae-plugin/audio/global-outflags",
        "ae-plugin/audio/audio-data-structures",
        "ae-plugin/audio/audio-specific-float-slider-variables",
        "ae-plugin/audio/accessing-audio-data",
        "ae-plugin/audio/audio-considerations",
      ],
    },
    {
      label: "AEGPs",
      items: [
        "ae-plugin/aegps/aegps",
        "ae-plugin/aegps/overview",
        "ae-plugin/aegps/data-types",
        "ae-plugin/aegps/implementation",
        "ae-plugin/aegps/aegp-suites",
        "ae-plugin/aegps/cheating-effect-usage-of-aegp-suites",
        "ae-plugin/aegps/aegp-details",
      ],
    },
    {
      label: "Artisans",
      items: ["ae-plugin/artisans/artisans", "ae-plugin/artisans/artisan-data-types"],
    },
    {
      label: "AEIOs",
      items: [
        "ae-plugin/aeios/aeios",
        "ae-plugin/aeios/calling-sequence",
        "ae-plugin/aeios/aeio_moduleinfo",
        "ae-plugin/aeios/new-kids-on-the-function-block",
        "ae-plugin/aeios/implementation-details",
      ],
    },
    {
      label: "Premiere Pro",
      items: [
        "ae-plugin/ppro/ppro",
        "ae-plugin/ppro/plug-in-installation",
        "ae-plugin/ppro/basic-host-differences",
        "ae-plugin/ppro/multithreading",
        "ae-plugin/ppro/bigger-differences",
        "ae-plugin/ppro/plug-ins-reloaded",
        "ae-plugin/ppro/premiere-elements",
        "ae-plugin/ppro/unsupported-features",
        "ae-plugin/ppro/other-hosts",
      ],
    },
  ],
};
