export const javascriptTools = {
  label: "javascript-tools",
  link: "javascript-tools/introduction/extendscript-overview",
  icon: "open-book",
  items: [
    {
      label: "Introduction",
      items: ["javascript-tools/introduction/extendscript-overview", "javascript-tools/introduction/scripting-for-specific-applications"],
    },
    {
      label: "The VS Code ExtendScript Debugger",
      items: [
        "javascript-tools/vscode-debugger",
        "javascript-tools/vscode-debugger/getting-started-with-vscode-debugger",
        "javascript-tools/vscode-debugger/vscode-extension-features",
      ],
    },
    {
      label: "The ExtendScript Toolkit",
      items: [
        "javascript-tools/extendscript-toolkit",
        "javascript-tools/extendscript-toolkit/configuring-the-toolkit-window",
        "javascript-tools/extendscript-toolkit/selecting-scripts",
        "javascript-tools/extendscript-toolkit/the-script-editor",
        "javascript-tools/extendscript-toolkit/debugging-in-the-toolkit",
        "javascript-tools/extendscript-toolkit/code-profiling-for-optimization",
        "javascript-tools/extendscript-toolkit/inspecting-object-models",
      ],
    },
    {
      label: "File System Access",
      items: [
        "javascript-tools/file-system-access",
        "javascript-tools/file-system-access/using-file-and-folder-objects",
        "javascript-tools/file-system-access/file-access-error-messages",
        "javascript-tools/file-system-access/file-and-folder-supported-encoding-names",
        "javascript-tools/file-system-access/file-object",
        "javascript-tools/file-system-access/folder-object",
      ],
    },
    {
      label: "User-Interface Tools",
      items: [
        "javascript-tools/user-interface-tools",
        "javascript-tools/user-interface-tools/code-examples-for-scriptui",
        "javascript-tools/user-interface-tools/scriptui-programming-model",
        "javascript-tools/user-interface-tools/types-of-controls",
        "javascript-tools/user-interface-tools/size-and-location-objects",
        "javascript-tools/user-interface-tools/drawing-objects",
        "javascript-tools/user-interface-tools/resource-specifications",
        "javascript-tools/user-interface-tools/defining-behavior-with-event-callbacks-and-listeners",
        "javascript-tools/user-interface-tools/communicating-with-the-flash-application",
        "javascript-tools/user-interface-tools/automatic-layout",
        "javascript-tools/user-interface-tools/managing-control-titles",
        "javascript-tools/user-interface-tools/localization-in-scriptui-objects",
        "javascript-tools/user-interface-tools/scriptui-object-reference",
        "javascript-tools/user-interface-tools/scriptui-class",
        "javascript-tools/user-interface-tools/environment",
        "javascript-tools/user-interface-tools/common-properties",
        "javascript-tools/user-interface-tools/window-class",
        "javascript-tools/user-interface-tools/window-object",
        "javascript-tools/user-interface-tools/control-objects",
        "javascript-tools/user-interface-tools/event-handling",
        "javascript-tools/user-interface-tools/graphic-customization-objects",
        "javascript-tools/user-interface-tools/layoutmanager-object",
      ],
    },
    {
      label: "Interapplication Communication with Scripts",
      items: [
        "javascript-tools/interapplication-communication",
        "javascript-tools/interapplication-communication/communications-overview",
        "javascript-tools/interapplication-communication/cross-dom-functions",
        "javascript-tools/interapplication-communication/communicating-through-messages",
        "javascript-tools/interapplication-communication/messaging-framework-api-reference",
        "javascript-tools/interapplication-communication/bridgetalk-class",
        "javascript-tools/interapplication-communication/bridgetalk-message-object",
        "javascript-tools/interapplication-communication/messaging-error-codes",
        "javascript-tools/interapplication-communication/application-and-namespace-specifiers",
      ],
    },
    {
      label: "External Communication Tools",
      items: [
        "javascript-tools/external-communication",
        "javascript-tools/external-communication/socket-object",
        "javascript-tools/external-communication/socket-object-reference",
      ],
    },
    {
      label: "Integrating External Libraries",
      items: [
        "javascript-tools/integrating-external-libraries",
        "javascript-tools/integrating-external-libraries/loading-and-using-shared-libraries",
        "javascript-tools/integrating-external-libraries/externalobject-object",
        "javascript-tools/integrating-external-libraries/defining-entry-points-for-direct-access",
        "javascript-tools/integrating-external-libraries/defining-entry-points-for-indirect-access",
      ],
    },
    {
      label: "ExtendScript Tools and Features",
      items: [
        "javascript-tools/extendscript-tools-features",
        "javascript-tools/extendscript-tools-features/dollar-object",
        "javascript-tools/extendscript-tools-features/extendscript-reflection-interface",
        "javascript-tools/extendscript-tools-features/localizing-extendscript-strings",
        "javascript-tools/extendscript-tools-features/user-notification-dialogs",
        "javascript-tools/extendscript-tools-features/specifying-measurement-values",
        "javascript-tools/extendscript-tools-features/preprocessor-directives",
        "javascript-tools/extendscript-tools-features/operator-overloading",
      ],
    },
    {
      label: "Integrating XML into JavaScript",
      items: [
        "javascript-tools/integrating-xml",
        "javascript-tools/integrating-xml/the-xml-object",
        "javascript-tools/integrating-xml/xml-object-reference",
      ],
    },
    {
      label: "Scripting Access to XMP Metadata",
      items: [
        "javascript-tools/scripting-xmp",
        "javascript-tools/scripting-xmp/accessing-the-xmp-scripting-api",
        "javascript-tools/scripting-xmp/xmpscript-object-reference",
      ],
    },
  ],
};
