export const prPlugin = {
  label: "Pr插件开发",
  link: "pr-plugin/intro/what-premiere-plugins-do",
  icon: "puzzle",
  items: [
    {
      label: "Introduction",
      items: [
        "pr-plugin/intro/what-premiere-plugins-do",
        "pr-plugin/intro/sdk-audience",
        "pr-plugin/intro/whats-new",
        "pr-plugin/intro/where-do-i-start",
        "pr-plugin/intro/document-overview",
        "pr-plugin/intro/getting-support",
        "pr-plugin/intro/premiere-pro-plugin-types",
        "pr-plugin/intro/sample-projects",
        "pr-plugin/intro/debugging-plugins",
        "pr-plugin/intro/load-em-up",
        "pr-plugin/intro/plugin-installation",
        "pr-plugin/intro/localization",
        "pr-plugin/intro/best-practices",
      ],
    },
    {
      label: "Resources",
      items: ["pr-plugin/resources/resources", "pr-plugin/resources/pipl-resource", "pr-plugin/resources/impt-resource"],
    },
    {
      label: "Universals",
      items: [
        "pr-plugin/universals/universals",
        "pr-plugin/universals/time",
        "pr-plugin/universals/video-frames",
        "pr-plugin/universals/pixel-formats-and-color-spaces",
        "pr-plugin/universals/pixel-aspect-ratio",
        "pr-plugin/universals/fields",
        "pr-plugin/universals/audio",
        "pr-plugin/universals/memory-management",
        "pr-plugin/universals/basic-types-structures",
        "pr-plugin/universals/suites",
        "pr-plugin/universals/sweetpea-suites",
        "pr-plugin/universals/legacy-callback-suites",
      ],
    },
    {
      label: "Hardware Integration",
      items: [
        "pr-plugin/hardware/hardware",
        "pr-plugin/hardware/hardware-integration-components",
        "pr-plugin/hardware/classid-filetype-subtype",
        "pr-plugin/hardware/classdata-functions",
      ],
    },
    {
      label: "Importers",
      items: [
        "pr-plugin/importers/importers",
        "pr-plugin/importers/whats-new",
        "pr-plugin/importers/getting-started",
        "pr-plugin/importers/selector-table",
        "pr-plugin/importers/selector-descriptions",
        "pr-plugin/importers/return-codes",
        "pr-plugin/importers/structures",
        "pr-plugin/importers/structure-descriptions",
        "pr-plugin/importers/suites",
      ],
    },
    {
      label: "Export Controllers",
      items: ["pr-plugin/export-controllers/export-controllers"],
    },
    {
      label: "Exporters",
      items: [
        "pr-plugin/exporters/exporters",
        "pr-plugin/exporters/whats-new",
        "pr-plugin/exporters/getting-started",
        "pr-plugin/exporters/selector-table",
        "pr-plugin/exporters/selector-descriptions",
        "pr-plugin/exporters/return-codes",
        "pr-plugin/exporters/structures",
        "pr-plugin/exporters/structure-descriptions",
        "pr-plugin/exporters/suites",
        "pr-plugin/exporters/additional-details",
      ],
    },
    {
      label: "Transmitters",
      items: [
        "pr-plugin/transmitters/transmitters",
        "pr-plugin/transmitters/transmitter-basics",
        "pr-plugin/transmitters/tmmodule-functions",
        "pr-plugin/transmitters/tmmodule-structures",
        "pr-plugin/transmitters/suites",
      ],
    },
    {
      label: "Video Filters",
      items: [
        "pr-plugin/video-filters/video-filters",
        "pr-plugin/video-filters/whats-new",
        "pr-plugin/video-filters/getting-started",
        "pr-plugin/video-filters/selector-table",
        "pr-plugin/video-filters/selector-descriptions",
        "pr-plugin/video-filters/return-codes",
        "pr-plugin/video-filters/videorecord",
        "pr-plugin/video-filters/additional-details",
      ],
    },
    {
      label: "GPU Effects & Transitions",
      items: [
        "pr-plugin/gpu-effects-transitions/gpu-effects-transitions",
        "pr-plugin/gpu-effects-transitions/getting-started",
        "pr-plugin/gpu-effects-transitions/cuda-opencl-metal-opengl",
        "pr-plugin/gpu-effects-transitions/whats-new-in-ppro-12",
        "pr-plugin/gpu-effects-transitions/whats-new-in-ppro-cc2015",
        "pr-plugin/gpu-effects-transitions/whats-new-in-ppro-cc2014",
        "pr-plugin/gpu-effects-transitions/prgpufilter-function-table",
        "pr-plugin/gpu-effects-transitions/function-descriptions",
        "pr-plugin/gpu-effects-transitions/return-codes",
        "pr-plugin/gpu-effects-transitions/structure-descriptions",
        "pr-plugin/gpu-effects-transitions/prgpu-sdk-macros",
        "pr-plugin/gpu-effects-transitions/suites",
      ],
    },
    {
      label: "AE Transition Extensions",
      items: [
        "pr-plugin/ae-transition-extensions/getting-started",
        "pr-plugin/ae-transition-extensions/ae-transition-extensions",
        "pr-plugin/ae-transition-extensions/pf_transitionsuite",
      ],
    },
    {
      label: "Control Surfaces",
      items: ["pr-plugin/control-surfaces/control-surfaces"],
    },
  ],
};
